I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2, in script
    define narrator = Character (what_italic = true)
  File "game/script.rpy", line 2, in script
    define narrator = Character (what_italic = true)
  File "game/script.rpy", line 2, in <module>
    define narrator = Character (what_italic = true)
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 2, in script
    define narrator = Character (what_italic = true)
  File "game/script.rpy", line 2, in script
    define narrator = Character (what_italic = true)
  File "renpy/ast.py", line 2164, in execute
    self.set()
  File "renpy/ast.py", line 2175, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2, in <module>
    define narrator = Character (what_italic = true)
NameError: name 'true' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.1.1270
NoirDog 1.0
Fri Jan 29 19:33:04 2021
